
from langchain.tools import tool
from src.config.llm import llm
from src.agents.reasoning_agent import reasoning_agent as reasoning_graph
from src.agents.calculator_agent import calculator_agent as calculator_graph
from src.agents.reviewer_agent import reviewer_agent as reviewer_graph
@tool
def reasoning_agent(query: str, history: list = None) -> str:
    """
    Handle mathematical reasoning and conversation memory.

    Use this skill for:
    - Math problem analysis
    - Logical reasoning
    - Extracting values from math questions
    - Understanding follow-up questions using chat history
    - Answering questions about previous messages

    Examples:
    - Solve x² + 5x + 6 = 0
    - Calculate compound interest
    - What was my last message?
    - What did I ask before?
    - Explain the previous answer

    Uses conversation history when available to provide context-aware responses.
    """
    result = reasoning_graph.invoke(
        {
            "messages": [
                {
                    "role": "user",
                    "content": query,
                    "history" : history,
                }
            ]
        }
    )

    return result["messages"][-1].content

@tool
def calculator_agent(
    query : str,
    history: list = None
):
    """
    Perform mathematical calculations based on structured input.

    Use this skill when the user needs:
    - Arithmetic calculations
    - Percentage calculations
    - Profit and loss calculations
    - Simple and compound interest calculations
    - Algebraic computations
    - Statistical calculations
    - Numerical evaluation of formulas
    - Verification of mathematical results

    Examples:
    - Calculate 25 * 48
    - Find compound interest on 10000 at 8% for 3 years
    - Calculate profit percentage
    - Evaluate a mathematical expression
    - Compute the final answer from extracted values

    This tool focuses on performing accurate calculations.
    It should not provide explanations or reasoning.
    It returns calculation results only.
    """


    result = calculator_graph.invoke(
        {
            "messages" : [
                {
                    "role" : "user",
                    "content" : query,
                    "history" : history,
                }
            ]
        }
    )

    return result["messages"][-1].content

@tool
def reviewer_agent(
    query: str,
    history: list = None
):
    """
    Review, validate, and improve answers generated by other agents.

    Use this skill when:
    - Checking mathematical calculations
    - Verifying reasoning steps
    - Detecting logical errors
    - Validating final answers
    - Ensuring consistency between reasoning and calculations
    - Identifying missing information
    - Improving answer quality and accuracy

    Examples:
    - Verify a compound interest calculation
    - Check whether the reasoning is correct
    - Review the final solution before returning it
    - Detect mistakes in calculations
    - Validate extracted values and computed results

    This tool acts as a quality-control reviewer.
    It should analyze outputs from other agents and provide
    a corrected, validated, and reliable final response.
    """


    result = reviewer_graph.invoke(
        {
            "messages": [
                {
                    "role": "user",
                    "content": query,
                    "history" : history,
                }
            ]
        }
    )

    return result["messages"][-1].content